port = 3001

workers = 3

result-store-dir = "/tmp/ncml"

[jwt-auth]
    enabled = true
	secret = "abc"
	
# Setup Credential sets 
[credentials]
	
    [credentials."cred-set-1"]
    username = "test-user"
    password = "abc"
	
	[credentials."cred-set-2"]
    username = "test-user-2"
    password = "def"

    [credentials."local"]
    username = "test"
    password = "ghi"

[db]
type = "postgres" # or sqlserver
host = "localhost"
port = 5432
ssl-mode = false
username = "postgres"
password = "docker"
dbname = "ncml"

[ping]
privileged = false
timeout-sec = 60

[log]
format = "text" # valid values are text or json
output = "term" # valid values are term or file
#log-directory = "./logs/" # needed if writing logs to a file
level = "debug"